### ISSUE TITLE
Categorization of question types

### ISSUE THREAD

**Issue by masashi-y** [allenai/modularqa#1]
Hello, thank you for sharing the great work!

I find the published DROP/HotpotQA subset datasets very useful for my own project and would love to use those. Thank you for sharing these too.
By the way, in the paper I find the questions are categorized into Diff/Comp/Cmpl classes and the numbers are reported based on those.
I would like to do the same but cannot find those class labels in the files.
Could those infos be available as well?

Thanks!

**Comment by tusharkhot** [comment]
@masashi-y Thank you for your interest. I have uploaded the evaluation partitions of the DROP dataset at:
https://ai2-public-datasets.s3.amazonaws.com/modularqa/drop_partitions.zip

Also added to [README](https://github.com/allenai/modularqa/commit/4571ad3be015037a69d32a8ac24131a2f13f20f9)

**Comment by masashi-y** [comment]
Thank you!
